[workspace]
members = [
  "pkarr", "relay", "bindings/js",
]

# See: https://github.com/rust-lang/rust/issues/90148#issuecomment-949194352
resolver = "2"

[workspace.metadata.crane]
name = "pkarr"

[workspace.dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
# WASM dependencies - shared directly or transitively
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.50"
