[package]
name = "pkarr-relay"
version = "0.10.0"
authors = ["Nuh <nuh@nuh.dev>"]
edition = "2021"
description = "Pkarr relay (https://pkarr.org/relays)"
license = "MIT"
homepage = "https://pkarr.org"
repository = "https://git.pkarr.org"
keywords = ["pkarr", "relay", "mainline", "dht"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.95"
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
axum-server = { version = "0.7.1", features = ["tls-rustls-no-provider"] }
rustls = { workspace = true }
http = "1.2.0"
thiserror = "2.0.11"
bytes = "1.10.0"
tower_governor = "0.6.0"
governor = "0.8.0"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.20"
clap = { version = "4.5.28", features = ["derive"] }
dirs-next = "2.0.0"
httpdate = "1.0.3"
url = "2.5.4"
pkarr = { version = "3.8.0", default-features = false, features = ["dht", "lmdb-cache"] }

[package.metadata.docs.rs]
all-features = true
