name: WASM Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build server
      run: cargo build

    - name: Build WASM package
      run: |
        cd ./pkarr
        chmod +x build-wasm.sh
        ./build-wasm.sh

    - name: Start server and run all tests
      run: |
        # Start the server binary in the background
        ./target/debug/pkarr-relay --testnet &
        SERVER_PID=$!
        
        # Ensure server gets killed on exit
        trap "kill $SERVER_PID" EXIT
        
        # Wait for server to start
        sleep 2
        
        # Change the working directory to pkarr crate
        cd ./pkarr
        
        # Run wasm-pack tests (Rust WASM tests)
        echo "🦀 Running Rust WASM tests..."
        wasm-pack test --headless --firefox --lib
        
        # Change to the pkg directory and run JavaScript tests
        echo "🟨 Running JavaScript tests..."
        cd pkg
        npm run test
        
        echo "✅ All tests completed successfully!"

